title: Ria Jennifer
logo: /assets/img/logo.png
description: A highly skilled Technical Support Executive offering support and solutions to customer queries, especially pertaining to Hardware, Systems Administration, Quality and Networking; excellent time management skills; proficient in computer skills; excellent organizational skills.
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
